<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Atlas.Blazor" Version="0.2.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.36" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.36" />
    <PackageVersion Include="SkiaSharp.Views.Blazor" Version="2.88.9" />
    <PackageVersion Include="SkiaSharp" Version="2.88.9" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="2.88.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
