<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Penelopa.Core\Penelopa.Core.csproj" />
  </ItemGroup>

</Project>
