name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - run: dotnet workload install wasm-tools
      - run: dotnet restore Penelopa.sln
      - run: dotnet build Penelopa.sln --no-restore
      - run: dotnet test Penelopa.sln --no-build --no-restore

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - run: dotnet workload install wasm-tools
      - run: dotnet restore Penelopa.sln
      - run: dotnet format Penelopa.sln --verify-no-changes --no-restore
